### ISSUE TITLE
Support google map

### ISSUE THREAD

**Issue by centratelemedia** [KarthikeyanRanasthala/solid-bottomsheet#5]
we have problem when using google map, i can't click map...

**Comment by ericwaetke** [comment]
Without knowing anything further about this (please provide additional infos), I’d assume, you haven’t changed the default css. Thus, user’s clicks trigger the backdrop overlay and close the overlay. And since you don’t want that to happen, you’d have to change that behaviour

**Comment by ericwaetke** [comment]
I just saw that this is also a todo in the readme:
`(Feat) Non-blocking view`

**Comment by ericwaetke** [comment]
In the CSS change these things:

```css
.sb-overlay {
	…
	/* background-color: rgba(0, 0, 0, 0.5); */
	pointer-events: none;
}
.sb-content {
	…
	pointer-events: all;
}

```
